// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[categ].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/create.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/resenias/[rutaId].tsx";
import * as $6 from "./routes/resenias/[rutaId]/create-resenia.tsx";
import * as $$0 from "./islands/Carousel.tsx";
import * as $$1 from "./islands/ReseniaCard.tsx";
import * as $$2 from "./islands/RouteCard.tsx";

const manifest = {
  routes: {
    "./routes/[categ].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/create.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/resenias/[rutaId].tsx": $5,
    "./routes/resenias/[rutaId]/create-resenia.tsx": $6,
  },
  islands: {
    "./islands/Carousel.tsx": $$0,
    "./islands/ReseniaCard.tsx": $$1,
    "./islands/RouteCard.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
